### ISSUE TITLE
FAQ Page bottom

### ISSUE THREAD

**Issue by vrr-21** [kartik2112/CompsDeptLib#11]
# !IMPORTANT

At the bottom of the FAQ Page, the details of the librarian are mentioned.
The Departmental Library is said to be in Room number 107, B-Building:

>For any further help, contact the librarian:
>Librarian: Mrs. Nutan Dhuri
>Extension number: 9091
>E-mail ID: nutandhuri@somaiya.edu
>The computer departmental library is in room number 107, B-building.

This is wrong, and needs to be changed with appropriate data.

**Comment by kartik2112** [comment]
What is wrong in this?

**Comment by kartik2112** [comment]
okay got it dept lib room
right that's wrong

**Comment by kartik2112** [comment]
Ho gaya?

**Comment by dev-td7** [comment]
B119  has been shown. To I guess its done!
